/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include<stdio.h>
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0   (GUI_ID_USER + 0x00)
#define ID_BUTTON_0   (GUI_ID_USER + 0x01)
#define ID_TEXT_0   (GUI_ID_USER + 0x02)
#define ID_TEXT_1   (GUI_ID_USER + 0x03)
#define ID_TEXT_2   (GUI_ID_USER + 0x04)
#define ID_TEXT_3   (GUI_ID_USER + 0x05)
#define ID_TEXT_4   (GUI_ID_USER + 0x06)
#define ID_TEXT_5   (GUI_ID_USER + 0x07)
#define ID_TEXT_6   (GUI_ID_USER + 0x08)
#define ID_TEXT_7   (GUI_ID_USER + 0x09)
#define ID_TEXT_8   (GUI_ID_USER + 0x0A)
#define ID_BUTTON_1   (GUI_ID_USER + 0x0B)
#define ID_BUTTON_2   (GUI_ID_USER + 0x0C)
#define ID_TEXT_9   (GUI_ID_USER + 0x0D)
#define ID_BUTTON_3   (GUI_ID_USER + 0x0E)
#define ID_TEXT_10   (GUI_ID_USER + 0x0F)
#define ID_TEXT_11   (GUI_ID_USER + 0x10)


// USER START (Optionally insert additional defines)
//#include <stdio.h>
//uint16_t buffer; 
//
//RTC_TimeTypeDef sTime;//定义时间结构体
//RTC_DateTypeDef sDate;

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
//int data = 0;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 18, 12, 480, 272, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "SPEED", ID_BUTTON_0, 235, 224, 120, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "N_TEM", ID_TEXT_0, 74, 45, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "N_HUM", ID_TEXT_1, 290, 46, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "M", ID_TEXT_2, 96, 188, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "S", ID_TEXT_3, 97, 229, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "N_TEM", ID_TEXT_4, 17, 45, 53, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "N_HUM", ID_TEXT_5, 197, 46, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "N_MODEL", ID_TEXT_6, 16, 188, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "N_SPEED", ID_TEXT_7, 15, 230, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "SET_TEM", ID_TEXT_8, 13, 112, 91, 19, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "+", ID_BUTTON_1, 177, 88, 90, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "-", ID_BUTTON_2, 297, 90, 90, 60, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "print tem", ID_TEXT_9, 71, 94, 94, 46, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "MODEL", ID_BUTTON_3, 235, 173, 120, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "DATE", ID_TEXT_10, 190, 8, 134, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "TIME", ID_TEXT_11, 332, 9, 103, 22, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    //
    // Initialization of 'N_TEM'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "2");
    //
    // Initialization of 'N_HUM'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetText(hItem, "3");
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'M'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "MODEL");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'S'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "SPEED");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'N_TEM'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetText(hItem, "N_TEM");
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'N_HUM'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    TEXT_SetText(hItem, "N_HUM");
    //
    // Initialization of 'N_MODEL'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetText(hItem, "N_MODEL");
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'N_SPEED'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetText(hItem, "N_SPEED");
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'SET_TEM'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetText(hItem, "SET_TEM");
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of '+'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetText(hItem, "rise");
    //
    // Initialization of '-'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetText(hItem, "reduce");
    //
    // Initialization of 'print tem'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
    TEXT_SetFont(hItem, GUI_FONT_24_1);
    TEXT_SetText(hItem, "18");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'DATE'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
    TEXT_SetText(hItem, "0");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'TIME'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "1");
    // USER START (Optionally insert additional code for further widget initialization)
 
//  case WM_TIMER:    //屏幕时间显示
//    
//    WM_RestartTimer(pMsg->Data.v,100);
//    HAL_RTC_GetTime(&hrtc, &sTime, RTC_FORMAT_BIN);
//    HAL_RTC_GetDate(&hrtc, &sDate, RTC_FORMAT_BIN);    
//    
//    sprintf(buffer,"%02d:%02d:%02d\r\n",sTime.Hours, sTime.Minutes, sTime.Seconds);
//    TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_11),buffer);
//    
//    sprintf(buffer,"%02d:%02d:%02d\r\n",2000 + sDate.Year, sDate.Month, sDate.Date);
//    TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_10),buffer);
    
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'SPEED'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by '+'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by '-'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'MODEL'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
