/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.44                      *
*        Compiled Nov 10 2017, 08:53:23                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: name.c                                                *
* Font:        微软雅黑 Light                                        *
* Height:      19                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  19                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: D:\GCX\source\STM32CubeMX\20201101\高成鑫 孙天一.txt*
* Range enabled:        0020 - 0080                                  *
* Read pattern file: D:\GCX\source\STM32CubeMX\20201101\高成鑫 孙天一.txt*
* Read pattern file: D:\GCX\source\STM32CubeMX\20201101\高成鑫 孙天一.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontname;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Fontname_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0021[ 10] = { /* code 0021, EXCLAMATION MARK */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  ________,
  ________,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0022[  3] = { /* code 0022, QUOTATION MARK */
  X_X_____,
  X_X_____,
  X_X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0023[  9] = { /* code 0023, NUMBER SIGN */
  ___X_X__,
  ___X_X__,
  ___X_X__,
  _XXXXXX_,
  __X_X___,
  XXXXXX__,
  _X_X____,
  _X_X____,
  _X_X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0024[ 12] = { /* code 0024, DOLLAR SIGN */
  __X_____,
  _XXXX___,
  X_X_____,
  X_X_____,
  X_X_____,
  _XX_____,
  __XX____,
  __X_X___,
  __X_X___,
  __X_X___,
  XXXX____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0025[ 20] = { /* code 0025, PERCENT SIGN */
  _XXX___X,________,
  X___X_X_,________,
  X___X_X_,________,
  X___XX__,________,
  _XXX_X__,________,
  ____X_XX,X_______,
  ____XX__,_X______,
  ___X_X__,_X______,
  ___X_X__,_X______,
  __X___XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0026[ 20] = { /* code 0026, AMPERSAND */
  __XXX___,________,
  _X___X__,________,
  _X___X__,________,
  _X__X___,________,
  __XX____,________,
  _X_X___X,________,
  X___X__X,________,
  X____XX_,________,
  XX___XX_,________,
  _XXXX__X,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0027[  3] = { /* code 0027, APOSTROPHE */
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0028[ 12] = { /* code 0028, LEFT PARENTHESIS */
  __X_____,
  _X______,
  _X______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  _X______,
  _X______,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0029[ 12] = { /* code 0029, RIGHT PARENTHESIS */
  X_______,
  _X______,
  _X______,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  _X______,
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_002A[  6] = { /* code 002A, ASTERISK */
  ___X____,
  ___X____,
  XX_XXX__,
  __XX____,
  __XX____,
  _X__X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_002B[  7] = { /* code 002B, PLUS SIGN */
  ___X____,
  ___X____,
  ___X____,
  XXXXXXX_,
  ___X____,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_002C[  3] = { /* code 002C, COMMA */
  _X______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_002D[  1] = { /* code 002D, HYPHEN-MINUS */
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_002E[  1] = { /* code 002E, FULL STOP */
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_002F[ 12] = { /* code 002F, SOLIDUS */
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  _X______,
  _X______,
  _X______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0030[ 10] = { /* code 0030, DIGIT ZERO */
  __XXX___,
  _X__X___,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  _X__X___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0031[ 10] = { /* code 0031, DIGIT ONE */
  __X_____,
  XXX_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0032[ 10] = { /* code 0032, DIGIT TWO */
  __XX____,
  _X__X___,
  ____X___,
  ____X___,
  ____X___,
  ___X____,
  __X_____,
  _X______,
  X_______,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0033[ 10] = { /* code 0033, DIGIT THREE */
  XXXX____,
  ___XX___,
  ____X___,
  ____X___,
  ___X____,
  _XX_____,
  ___XX___,
  ____X___,
  ____X___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0034[ 10] = { /* code 0034, DIGIT FOUR */
  _____X__,
  ____XX__,
  ___X_X__,
  ___X_X__,
  __X__X__,
  _X___X__,
  X____X__,
  XXXXXXX_,
  _____X__,
  _____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0035[ 10] = { /* code 0035, DIGIT FIVE */
  XXXXX___,
  X_______,
  X_______,
  X_______,
  XXXX____,
  ___XX___,
  ____X___,
  ____X___,
  ___XX___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0036[ 10] = { /* code 0036, DIGIT SIX */
  __XXX___,
  _X______,
  XX______,
  X_______,
  X_XXX___,
  XX__XX__,
  X____X__,
  X____X__,
  _X__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0037[ 10] = { /* code 0037, DIGIT SEVEN */
  XXXXXX__,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0038[ 10] = { /* code 0038, DIGIT EIGHT */
  _XXXX___,
  X___XX__,
  X____X__,
  XX__XX__,
  __XX____,
  XX__X___,
  X____X__,
  X____X__,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0039[ 10] = { /* code 0039, DIGIT NINE */
  _XXXX___,
  _X__X___,
  X____X__,
  X____X__,
  X____X__,
  XX__XX__,
  _XXX_X__,
  _____X__,
  ____X___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_003A[  7] = { /* code 003A, COLON */
  X_______,
  ________,
  ________,
  ________,
  ________,
  ________,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_003B[  8] = { /* code 003B, SEMICOLON */
  _X______,
  ________,
  ________,
  ________,
  ________,
  _X______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_003C[  6] = { /* code 003C, LESS-THAN SIGN */
  ____X___,
  __XX____,
  _X______,
  _X______,
  __XX____,
  ____X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_003D[  4] = { /* code 003D, EQUALS SIGN */
  XXXXXXX_,
  ________,
  ________,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_003E[  6] = { /* code 003E, GREATER-THAN SIGN */
  X_______,
  _XX_____,
  ___X____,
  ___X____,
  _XX_____,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_003F[ 10] = { /* code 003F, QUESTION MARK */
  XXXX____,
  ____X___,
  ____X___,
  ____X___,
  ___X____,
  __X_____,
  __X_____,
  ________,
  ________,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0040[ 22] = { /* code 0040, COMMERCIAL AT */
  ___XXXXX,________,
  __X_____,XX______,
  _X__XXXX,XXX_____,
  X___X__X,X_X_____,
  X__X___X,__X_____,
  X__X___X,__X_____,
  X__X__XX,__X_____,
  X___XX_X,XX______,
  _X______,________,
  _XX_____,________,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0041[ 10] = { /* code 0041, LATIN CAPITAL LETTER A */
  ____X___,
  ___XX___,
  ___XX___,
  __X__X__,
  __X__X__,
  _X____X_,
  _XXXXXX_,
  _X____X_,
  X______X,
  X______X};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0042[ 10] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXX___,
  X____X__,
  X____X__,
  X___X___,
  XXXX____,
  X___XX__,
  X____X__,
  X____X__,
  X___XX__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0043[ 10] = { /* code 0043, LATIN CAPITAL LETTER C */
  ___XXXX_,
  _XX_____,
  _X______,
  X_______,
  X_______,
  X_______,
  X_______,
  XX______,
  _XX_____,
  __XXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0044[ 10] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXX___,
  X____XX_,
  X_____XX,
  X______X,
  X______X,
  X______X,
  X______X,
  X_____X_,
  X____XX_,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0045[ 10] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXX___,
  X_______,
  X_______,
  X_______,
  XXXX____,
  X_______,
  X_______,
  X_______,
  X_______,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0046[ 10] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXXX___,
  X_______,
  X_______,
  X_______,
  XXXXX___,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0047[ 10] = { /* code 0047, LATIN CAPITAL LETTER G */
  __XXXXX_,
  _XX_____,
  _X______,
  X_______,
  X_______,
  X___XXX_,
  X_____X_,
  XX____X_,
  _X____X_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0048[ 10] = { /* code 0048, LATIN CAPITAL LETTER H */
  X______X,
  X______X,
  X______X,
  X______X,
  XXXXXXXX,
  X______X,
  X______X,
  X______X,
  X______X,
  X______X};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0049[ 10] = { /* code 0049, LATIN CAPITAL LETTER I */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_004A[ 10] = { /* code 004A, LATIN CAPITAL LETTER J */
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __XX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_004B[ 10] = { /* code 004B, LATIN CAPITAL LETTER K */
  X____X__,
  X___X___,
  X__X____,
  X_X_____,
  XXX_____,
  XX______,
  XXX_____,
  X__X____,
  X___X___,
  X____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_004C[ 10] = { /* code 004C, LATIN CAPITAL LETTER L */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_004D[ 20] = { /* code 004D, LATIN CAPITAL LETTER M */
  X_______,_X______,
  XX______,XX______,
  XX______,XX______,
  X_X____X,_X______,
  X_X____X,_X______,
  X__X__X_,_X______,
  X__X__X_,_X______,
  X___XX__,_X______,
  X___XX__,_X______,
  X_______,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_004E[ 10] = { /* code 004E, LATIN CAPITAL LETTER N */
  X______X,
  XX_____X,
  X_X____X,
  X_X____X,
  X__X___X,
  X___X__X,
  X____X_X,
  X____X_X,
  X_____XX,
  X______X};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_004F[ 20] = { /* code 004F, LATIN CAPITAL LETTER O */
  __XXXXX_,________,
  _XX___XX,________,
  _X_____X,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  XX_____X,________,
  _XX___XX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0050[ 10] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXXX___,
  X___XX__,
  X____X__,
  X____X__,
  X___XX__,
  XXXXX___,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0051[ 22] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ___XXXXX,________,
  _XX____X,X_______,
  _X______,XX______,
  X_______,_X______,
  X_______,_X______,
  X_______,_X______,
  X_______,_X______,
  _X______,X_______,
  _XX____X,X_______,
  ___XXXXX,________,
  ________,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0052[ 10] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXXX___,
  X___XX__,
  X____X__,
  X____X__,
  X___XX__,
  XXXX____,
  X__X____,
  X___X___,
  X___X___,
  X____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0053[ 10] = { /* code 0053, LATIN CAPITAL LETTER S */
  _XXXX___,
  X_______,
  X_______,
  X_______,
  _XX_____,
  __XX____,
  ____X___,
  ____X___,
  ____X___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0054[ 10] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXXX_,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0055[ 10] = { /* code 0055, LATIN CAPITAL LETTER U */
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  _X___X__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0056[ 10] = { /* code 0056, LATIN CAPITAL LETTER V */
  X______X,
  X______X,
  _X____X_,
  _X____X_,
  _X___X__,
  __X__X__,
  __X__X__,
  ___XX___,
  ___XX___,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0057[ 20] = { /* code 0057, LATIN CAPITAL LETTER W */
  X_____X_,____X___,
  X_____X_,____X___,
  _X___X_X,___X____,
  _X___X_X,___X____,
  _X___X_X,___X____,
  __X_X___,X_X_____,
  __X_X___,X_X_____,
  __X_X___,X_X_____,
  ___X____,_X______,
  ___X____,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0058[ 10] = { /* code 0058, LATIN CAPITAL LETTER X */
  X_____X_,
  _X___X__,
  __X__X__,
  __X_X___,
  ___X____,
  ___X____,
  __X_X___,
  _X___X__,
  _X___X__,
  X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0059[ 10] = { /* code 0059, LATIN CAPITAL LETTER Y */
  X_____X_,
  _X____X_,
  __X__X__,
  __X__X__,
  ___X_X__,
  ___XX___,
  ____X___,
  ____X___,
  ____X___,
  ____X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_005A[ 10] = { /* code 005A, LATIN CAPITAL LETTER Z */
  XXXXXXX_,
  _____X__,
  _____X__,
  ____X___,
  ___X____,
  ___X____,
  __X_____,
  _X______,
  _X______,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_005B[ 12] = { /* code 005B, LEFT SQUARE BRACKET */
  XXX_____,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_005C[ 11] = { /* code 005C, REVERSE SOLIDUS */
  X_______,
  X_______,
  _X______,
  _X______,
  __X_____,
  __X_____,
  __X_____,
  ___X____,
  ___X____,
  ____X___,
  ____X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_005D[ 12] = { /* code 005D, RIGHT SQUARE BRACKET */
  XXX_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_005E[  5] = { /* code 005E, CIRCUMFLEX ACCENT */
  __X_____,
  _X_X____,
  _X_X____,
  _X_X____,
  X___X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_005F[  1] = { /* code 005F, LOW LINE */
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0060[  2] = { /* code 0060, GRAVE ACCENT */
  X_______,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0061[  7] = { /* code 0061, LATIN SMALL LETTER A */
  _XXX____,
  ____X___,
  ____X___,
  _XXXX___,
  X___X___,
  X__XX___,
  _XX_X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0062[ 10] = { /* code 0062, LATIN SMALL LETTER B */
  X_______,
  X_______,
  X_______,
  X_XXXX__,
  XX___XX_,
  X_____X_,
  X_____X_,
  X_____X_,
  XX___X__,
  X_XXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0063[  7] = { /* code 0063, LATIN SMALL LETTER C */
  __XXX___,
  _X______,
  X_______,
  X_______,
  X_______,
  XX______,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0064[ 10] = { /* code 0064, LATIN SMALL LETTER D */
  _____X__,
  _____X__,
  _____X__,
  _XXX_X__,
  XX__XX__,
  X____X__,
  X____X__,
  X____X__,
  XX__XX__,
  _XXX_X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0065[  7] = { /* code 0065, LATIN SMALL LETTER E */
  _XXXX___,
  _X__XX__,
  X____X__,
  XXXXXX__,
  X_______,
  XX______,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0066[ 10] = { /* code 0066, LATIN SMALL LETTER F */
  __XX____,
  _X______,
  _X______,
  XXXX____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0067[ 10] = { /* code 0067, LATIN SMALL LETTER G */
  _XXX_X__,
  XX__XX__,
  X____X__,
  X____X__,
  X____X__,
  XX__XX__,
  _XXX_X__,
  _____X__,
  ____XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0068[ 10] = { /* code 0068, LATIN SMALL LETTER H */
  X_______,
  X_______,
  X_______,
  X_XXX___,
  XX___X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0069[ 10] = { /* code 0069, LATIN SMALL LETTER I */
  X_______,
  ________,
  ________,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_006A[ 13] = { /* code 006A, LATIN SMALL LETTER J */
  ___X____,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __XX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_006B[ 10] = { /* code 006B, LATIN SMALL LETTER K */
  X_______,
  X_______,
  X_______,
  X___X___,
  X_XX____,
  XX______,
  XX______,
  X_X_____,
  X__X____,
  X___X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_006C[ 10] = { /* code 006C, LATIN SMALL LETTER L */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_006D[ 14] = { /* code 006D, LATIN SMALL LETTER M */
  X_XXX_XX,X_______,
  XX__XXX_,_X______,
  X____X__,_X______,
  X____X__,_X______,
  X____X__,_X______,
  X____X__,_X______,
  X____X__,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_006E[  7] = { /* code 006E, LATIN SMALL LETTER N */
  X_XXX___,
  XX__XX__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_006F[  7] = { /* code 006F, LATIN SMALL LETTER O */
  _XXXX___,
  XX__XX__,
  X____X__,
  X____X__,
  X____X__,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0070[ 10] = { /* code 0070, LATIN SMALL LETTER P */
  X_XXXX__,
  XX___XX_,
  X_____X_,
  X_____X_,
  X_____X_,
  XX___X__,
  X_XXX___,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0071[ 10] = { /* code 0071, LATIN SMALL LETTER Q */
  _XXX_X__,
  XX__XX__,
  X____X__,
  X____X__,
  X____X__,
  XX__XX__,
  _XXX_X__,
  _____X__,
  _____X__,
  _____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0072[  7] = { /* code 0072, LATIN SMALL LETTER R */
  X_XX____,
  XX______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0073[  7] = { /* code 0073, LATIN SMALL LETTER S */
  _XXX____,
  X_______,
  X_______,
  _XX_____,
  ___X____,
  ___X____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0074[  9] = { /* code 0074, LATIN SMALL LETTER T */
  _X______,
  _X______,
  XXXX____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0075[  7] = { /* code 0075, LATIN SMALL LETTER U */
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  XX__XX__,
  _XXX_X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0076[  7] = { /* code 0076, LATIN SMALL LETTER V */
  X____X__,
  X____X__,
  _X__X___,
  _X__X___,
  __XX____,
  __XX____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0077[ 14] = { /* code 0077, LATIN SMALL LETTER W */
  X_______,_X______,
  X___XX__,_X______,
  _X__XX__,X_______,
  _X_X__X_,X_______,
  _X_X__X_,X_______,
  __XX__XX,________,
  __X____X,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0078[  7] = { /* code 0078, LATIN SMALL LETTER X */
  X____X__,
  _X__X___,
  __XX____,
  __X_____,
  __XX____,
  _X__X___,
  X____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_0079[ 10] = { /* code 0079, LATIN SMALL LETTER Y */
  X____X__,
  X____X__,
  _X__X___,
  _X__X___,
  __XX____,
  __XX____,
  __X_____,
  __X_____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_007A[  7] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXXXX_,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X______,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_007B[ 12] = { /* code 007B, LEFT CURLY BRACKET */
  __X_____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  X_______,
  _X______,
  _X______,
  _X______,
  _X______,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_007C[ 14] = { /* code 007C, VERTICAL LINE */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_007D[ 12] = { /* code 007D, RIGHT CURLY BRACKET */
  XX______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_007E[  2] = { /* code 007E, TILDE */
  XX__X___,
  X_XXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_007F[  1] = { /* code 007F, <control> */
  ________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontname_4E00[  2] = { /* code 4E00, <CJK Ideograph, First> */
  XXXXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_5207[ 26] = { /* code 5207 */
  __X_____,________,
  __X__XXX,XXXX____,
  __X____X,___X____,
  __XXX__X,___X____,
  XXX____X,___X____,
  __X____X,___X____,
  __X____X,___X____,
  __X____X,___X____,
  __X_X__X,___X____,
  __XX__X_,___X____,
  ______X_,___X____,
  _____X__,___X____,
  ____X___,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_5929[ 24] = { /* code 5929 */
  _XXXXXXX,XXXX____,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  XXXXXXXX,XXXXX___,
  ______X_,________,
  _____XX_,________,
  _____X_X,________,
  ____X__X,X_______,
  ___XX___,XX______,
  __XX____,_XX_____,
  _X______,___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_5B59[ 24] = { /* code 5B59 */
  ________,________,
  _XXXX___,X_______,
  ____X___,X_______,
  ___X____,X_______,
  __X___X_,X_X_____,
  __X___X_,X__X____,
  __XX__X_,X__X____,
  XXX__X__,X__X____,
  __X__X__,X___X___,
  __X_____,X_______,
  __X_____,X_______,
  XXX___XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_5F0F[ 26] = { /* code 5F0F */
  _______X,________,
  _______X,__X_____,
  _______X,__X_____,
  XXXXXXXX,XXXXX___,
  _______X,________,
  _______X,________,
  _XXXXXXX,________,
  ___X____,X_______,
  ___X____,X_______,
  ___X____,X_______,
  ___X_XX_,X___X___,
  XXX_X___,_X_X____,
  ________,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_6210[ 26] = { /* code 6210 */
  _______X,_X______,
  _______X,__X_____,
  __XXXXXX,XXXXX___,
  __X____X,________,
  __X____X,________,
  __XXXX_X,___X____,
  __X__X__,X_X_____,
  _X___X__,X_X_____,
  _X___X__,XX______,
  _X___X__,X_______,
  _X_XX___,X___X___,
  _X_____X,_X__X___,
  X_____X_,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_6362[ 26] = { /* code 6362 */
  __X____X,________,
  __X___XX,XXX_____,
  _XXX_X__,__X_____,
  __X__X__,_X______,
  __X__XXX,XXXX____,
  __X__X__,X__X____,
  __XX_X__,X__X____,
  XXX__X__,X__X____,
  __X_XXXX,XXXXX___,
  __X_____,X_______,
  __X____X,_X______,
  __X__XX_,__X_____,
  XX__X___,___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_6A21[ 26] = { /* code 6A21 */
  __X___X_,_X______,
  __X_XXXX,XXXX____,
  XXXX__X_,_X______,
  __X__XXX,XXXX____,
  __X__X__,___X____,
  _XXX_XXX,XXXX____,
  _XX_XX__,___X____,
  X_X__XXX,XXXX____,
  X_X_____,X_______,
  __X_XXXX,XXXX____,
  __X____X,X_______,
  __X___X_,_XX_____,
  __X_XX__,___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_946B[ 24] = { /* code 946B */
  _____XXX,________,
  ___XX___,XXX_____,
  _XX_____,___X____,
  _XXXXXXX,XXX_____,
  ___X__X_,_X______,
  _XXXXXXX,XXXX____,
  __XXX___,X_X_____,
  _XX_XXXX,X_XXX___,
  __XXX___,_X______,
  ___X____,XXX_____,
  _X_X_X_X,_XXX____,
  _XXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontname_9AD8[ 26] = { /* code 9AD8 */
  ______X_,________,
  XXXXXXXX,XXXXX___,
  ________,________,
  __XXXXXX,XX______,
  __X_____,__X_____,
  __XXXXXX,XX______,
  ________,________,
  _XXXXXXX,XXXX____,
  _X__XXXX,X__X____,
  _X__X___,X__X____,
  _X__XXXX,X__X____,
  _X______,___X____,
  _X______,_XXX____};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_Fontname_CharInfo[106] = {
   {   1,   1,   0,  15,   4, acGUI_Fontname_0020 } /* code 0020, SPACE */
  ,{   1,  10,   1,   5,   4, acGUI_Fontname_0021 } /* code 0021, EXCLAMATION MARK */
  ,{   3,   3,   1,   5,   5, acGUI_Fontname_0022 } /* code 0022, QUOTATION MARK */
  ,{   7,   9,   0,   5,   8, acGUI_Fontname_0023 } /* code 0023, NUMBER SIGN */
  ,{   5,  12,   1,   4,   7, acGUI_Fontname_0024 } /* code 0024, DOLLAR SIGN */
  ,{  10,  10,   1,   5,  11, acGUI_Fontname_0025 } /* code 0025, PERCENT SIGN */
  ,{   9,  10,   1,   5,  10, acGUI_Fontname_0026 } /* code 0026, AMPERSAND */
  ,{   1,   3,   1,   5,   3, acGUI_Fontname_0027 } /* code 0027, APOSTROPHE */
  ,{   3,  12,   1,   5,   4, acGUI_Fontname_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   3,  12,   0,   5,   4, acGUI_Fontname_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{   6,   6,   0,   5,   6, acGUI_Fontname_002A } /* code 002A, ASTERISK */
  ,{   7,   7,   1,   8,   9, acGUI_Fontname_002B } /* code 002B, PLUS SIGN */
  ,{   2,   3,   0,  13,   3, acGUI_Fontname_002C } /* code 002C, COMMA */
  ,{   4,   1,   1,  11,   6, acGUI_Fontname_002D } /* code 002D, HYPHEN-MINUS */
  ,{   1,   1,   1,  14,   3, acGUI_Fontname_002E } /* code 002E, FULL STOP */
  ,{   5,  12,   0,   5,   5, acGUI_Fontname_002F } /* code 002F, SOLIDUS */
  ,{   6,  10,   1,   5,   7, acGUI_Fontname_0030 } /* code 0030, DIGIT ZERO */
  ,{   3,  10,   1,   5,   5, acGUI_Fontname_0031 } /* code 0031, DIGIT ONE */
  ,{   5,  10,   1,   5,   7, acGUI_Fontname_0032 } /* code 0032, DIGIT TWO */
  ,{   5,  10,   1,   5,   7, acGUI_Fontname_0033 } /* code 0033, DIGIT THREE */
  ,{   7,  10,   0,   5,   7, acGUI_Fontname_0034 } /* code 0034, DIGIT FOUR */
  ,{   5,  10,   1,   5,   7, acGUI_Fontname_0035 } /* code 0035, DIGIT FIVE */
  ,{   6,  10,   1,   5,   7, acGUI_Fontname_0036 } /* code 0036, DIGIT SIX */
  ,{   6,  10,   0,   5,   7, acGUI_Fontname_0037 } /* code 0037, DIGIT SEVEN */
  ,{   6,  10,   1,   5,   7, acGUI_Fontname_0038 } /* code 0038, DIGIT EIGHT */
  ,{   6,  10,   1,   5,   7, acGUI_Fontname_0039 } /* code 0039, DIGIT NINE */
  ,{   1,   7,   1,   8,   3, acGUI_Fontname_003A } /* code 003A, COLON */
  ,{   2,   8,   0,   8,   3, acGUI_Fontname_003B } /* code 003B, SEMICOLON */
  ,{   5,   6,   2,   8,   9, acGUI_Fontname_003C } /* code 003C, LESS-THAN SIGN */
  ,{   7,   4,   1,   9,   9, acGUI_Fontname_003D } /* code 003D, EQUALS SIGN */
  ,{   5,   6,   2,   8,   9, acGUI_Fontname_003E } /* code 003E, GREATER-THAN SIGN */
  ,{   5,  10,   1,   5,   6, acGUI_Fontname_003F } /* code 003F, QUESTION MARK */
  ,{  11,  11,   1,   5,  13, acGUI_Fontname_0040 } /* code 0040, COMMERCIAL AT */
  ,{   8,  10,   0,   5,   9, acGUI_Fontname_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{   6,  10,   1,   5,   8, acGUI_Fontname_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{   7,  10,   1,   5,   9, acGUI_Fontname_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{   8,  10,   1,   5,   9, acGUI_Fontname_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{   5,  10,   1,   5,   7, acGUI_Fontname_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{   5,  10,   1,   5,   7, acGUI_Fontname_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{   7,  10,   1,   5,   9, acGUI_Fontname_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{   8,  10,   1,   5,  10, acGUI_Fontname_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   1,  10,   1,   5,   3, acGUI_Fontname_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{   4,  10,   0,   5,   5, acGUI_Fontname_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{   6,  10,   1,   5,   7, acGUI_Fontname_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{   4,  10,   1,   5,   6, acGUI_Fontname_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{  10,  10,   1,   5,  12, acGUI_Fontname_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{   8,  10,   1,   5,  10, acGUI_Fontname_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{   9,  10,   1,   5,  11, acGUI_Fontname_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{   6,  10,   1,   5,   8, acGUI_Fontname_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{  10,  11,   1,   5,  11, acGUI_Fontname_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{   6,  10,   1,   5,   8, acGUI_Fontname_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{   5,  10,   1,   5,   7, acGUI_Fontname_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{   7,  10,   0,   5,   7, acGUI_Fontname_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{   7,  10,   1,   5,   9, acGUI_Fontname_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{   8,  10,   0,   5,   8, acGUI_Fontname_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  13,  10,   0,   5,  13, acGUI_Fontname_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{   7,  10,   0,   5,   8, acGUI_Fontname_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{   7,  10,   0,   5,   8, acGUI_Fontname_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{   7,  10,   0,   5,   8, acGUI_Fontname_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   3,  12,   1,   5,   4, acGUI_Fontname_005B } /* code 005B, LEFT SQUARE BRACKET */
  ,{   5,  11,   0,   5,   5, acGUI_Fontname_005C } /* code 005C, REVERSE SOLIDUS */
  ,{   3,  12,   0,   5,   4, acGUI_Fontname_005D } /* code 005D, RIGHT SQUARE BRACKET */
  ,{   5,   5,   2,   5,   9, acGUI_Fontname_005E } /* code 005E, CIRCUMFLEX ACCENT */
  ,{   6,   1,   0,  17,   6, acGUI_Fontname_005F } /* code 005F, LOW LINE */
  ,{   2,   2,   1,   5,   3, acGUI_Fontname_0060 } /* code 0060, GRAVE ACCENT */
  ,{   5,   7,   1,   8,   7, acGUI_Fontname_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{   7,  10,   1,   5,   8, acGUI_Fontname_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{   5,   7,   1,   8,   6, acGUI_Fontname_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{   6,  10,   1,   5,   8, acGUI_Fontname_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{   6,   7,   1,   8,   7, acGUI_Fontname_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   4,  10,   0,   5,   4, acGUI_Fontname_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{   6,  10,   1,   8,   8, acGUI_Fontname_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{   6,  10,   1,   5,   8, acGUI_Fontname_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   1,  10,   1,   5,   3, acGUI_Fontname_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   4,  13,  -2,   5,   3, acGUI_Fontname_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{   5,  10,   1,   5,   6, acGUI_Fontname_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   1,  10,   1,   5,   3, acGUI_Fontname_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{  10,   7,   1,   8,  12, acGUI_Fontname_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{   6,   7,   1,   8,   8, acGUI_Fontname_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{   6,   7,   1,   8,   8, acGUI_Fontname_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{   7,  10,   1,   8,   8, acGUI_Fontname_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{   6,  10,   1,   8,   8, acGUI_Fontname_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{   4,   7,   1,   8,   5, acGUI_Fontname_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   4,   7,   1,   8,   5, acGUI_Fontname_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   4,   9,   0,   6,   4, acGUI_Fontname_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{   6,   7,   1,   8,   8, acGUI_Fontname_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{   6,   7,   0,   8,   6, acGUI_Fontname_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{  10,   7,   0,   8,  10, acGUI_Fontname_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{   6,   7,   0,   8,   6, acGUI_Fontname_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{   6,  10,   0,   8,   6, acGUI_Fontname_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{   7,   7,   0,   8,   7, acGUI_Fontname_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{   3,  12,   1,   5,   4, acGUI_Fontname_007B } /* code 007B, LEFT CURLY BRACKET */
  ,{   1,  14,   1,   4,   3, acGUI_Fontname_007C } /* code 007C, VERTICAL LINE */
  ,{   2,  12,   1,   5,   4, acGUI_Fontname_007D } /* code 007D, RIGHT CURLY BRACKET */
  ,{   5,   2,   2,  10,   9, acGUI_Fontname_007E } /* code 007E, TILDE */
  ,{   1,   1,   0,  15,   4, acGUI_Fontname_007F } /* code 007F, <control> */
  ,{  13,   1,   0,   9,  13, acGUI_Fontname_4E00 } /* code 4E00, <CJK Ideograph, First> */
  ,{  12,  13,   0,   4,  13, acGUI_Fontname_5207 } /* code 5207 */
  ,{  13,  12,   0,   5,  13, acGUI_Fontname_5929 } /* code 5929 */
  ,{  13,  12,   0,   4,  13, acGUI_Fontname_5B59 } /* code 5B59 */
  ,{  13,  13,   0,   4,  13, acGUI_Fontname_5F0F } /* code 5F0F */
  ,{  13,  13,   0,   4,  13, acGUI_Fontname_6210 } /* code 6210 */
  ,{  13,  13,   0,   4,  13, acGUI_Fontname_6362 } /* code 6362 */
  ,{  13,  13,   0,   4,  13, acGUI_Fontname_6A21 } /* code 6A21 */
  ,{  13,  12,   0,   4,  13, acGUI_Fontname_946B } /* code 946B */
  ,{  13,  13,   0,   4,  13, acGUI_Fontname_9AD8 } /* code 9AD8 */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontname_Prop11 = {
   0x9AD8 /* first character */
  ,0x9AD8 /* last character  */
  ,&GUI_Fontname_CharInfo[105] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontname_Prop10 = {
   0x946B /* first character */
  ,0x946B /* last character  */
  ,&GUI_Fontname_CharInfo[104] /* address of first character */
  ,&GUI_Fontname_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontname_Prop9 = {
   0x6A21 /* first character */
  ,0x6A21 /* last character  */
  ,&GUI_Fontname_CharInfo[103] /* address of first character */
  ,&GUI_Fontname_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontname_Prop8 = {
   0x6362 /* first character */
  ,0x6362 /* last character  */
  ,&GUI_Fontname_CharInfo[102] /* address of first character */
  ,&GUI_Fontname_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontname_Prop7 = {
   0x6210 /* first character */
  ,0x6210 /* last character  */
  ,&GUI_Fontname_CharInfo[101] /* address of first character */
  ,&GUI_Fontname_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontname_Prop6 = {
   0x5F0F /* first character */
  ,0x5F0F /* last character  */
  ,&GUI_Fontname_CharInfo[100] /* address of first character */
  ,&GUI_Fontname_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontname_Prop5 = {
   0x5B59 /* first character */
  ,0x5B59 /* last character  */
  ,&GUI_Fontname_CharInfo[ 99] /* address of first character */
  ,&GUI_Fontname_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontname_Prop4 = {
   0x5929 /* first character */
  ,0x5929 /* last character  */
  ,&GUI_Fontname_CharInfo[ 98] /* address of first character */
  ,&GUI_Fontname_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontname_Prop3 = {
   0x5207 /* first character */
  ,0x5207 /* last character  */
  ,&GUI_Fontname_CharInfo[ 97] /* address of first character */
  ,&GUI_Fontname_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontname_Prop2 = {
   0x4E00 /* first character */
  ,0x4E00 /* last character  */
  ,&GUI_Fontname_CharInfo[ 96] /* address of first character */
  ,&GUI_Fontname_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontname_Prop1 = {
   0x0020 /* first character */
  ,0x007F /* last character  */
  ,&GUI_Fontname_CharInfo[  0] /* address of first character */
  ,&GUI_Fontname_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontname = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,19 /* height of font  */
  ,19 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontname_Prop1}
  ,15 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,10 /* Height of capital characters */
};

