/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include<stdio.h>
#include "stm32f7xx_hal.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_BUTTON_0 (GUI_ID_USER + 0x01)
#define ID_TEXT_0 (GUI_ID_USER + 0x02)
#define ID_TEXT_1 (GUI_ID_USER + 0x03)
#define ID_TEXT_2 (GUI_ID_USER + 0x04)
#define ID_TEXT_3 (GUI_ID_USER + 0x05)
#define ID_TEXT_4 (GUI_ID_USER + 0x06)
#define ID_TEXT_5 (GUI_ID_USER + 0x07)
#define ID_TEXT_6 (GUI_ID_USER + 0x08)
#define ID_TEXT_7 (GUI_ID_USER + 0x09)
#define ID_TEXT_8 (GUI_ID_USER + 0x0A)
#define ID_BUTTON_1 (GUI_ID_USER + 0x0B)
#define ID_BUTTON_2 (GUI_ID_USER + 0x0C)
#define ID_TEXT_9 (GUI_ID_USER + 0x0D)
#define ID_BUTTON_3 (GUI_ID_USER + 0x0E)
#define ID_TEXT_10 (GUI_ID_USER + 0x0F)
#define ID_TEXT_11 (GUI_ID_USER + 0x10)
#define ID_TEXT_12 (GUI_ID_USER + 0x11)
#define ID_TEXT_13 (GUI_ID_USER + 0x12)
#define ID_TEXT_14 (GUI_ID_USER + 0x13)


// USER START (Optionally insert additional defines)
#include <stdio.h>
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
#define SWITCH_ON 200                            //开关红外的命令
#define SWITCH_OFF 201
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "SPEED", ID_BUTTON_0, 260, 220, 160, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "N_TEM", ID_TEXT_0, 83, 45, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "N_HUM", ID_TEXT_1, 290, 45, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "M", ID_TEXT_2, 104, 190, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "S", ID_TEXT_3, 344, 190, 65, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "N_TEM", ID_TEXT_4, 30, 45, 50, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "N_HUM", ID_TEXT_5, 197, 45, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "N_MODEL", ID_TEXT_6, 30, 190, 69, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "N_SPEED", ID_TEXT_7, 262, 190, 92, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "SET_TEM", ID_TEXT_8, 30, 121, 67, 19, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "+", ID_BUTTON_1, 168, 89, 120, 80, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "-", ID_BUTTON_2, 300, 89, 120, 80, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "print tem", ID_TEXT_9, 82, 105, 77, 46, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "MODEL", ID_BUTTON_3, 23, 220, 160, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "DATE", ID_TEXT_10, 226, 14, 122, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "TIME", ID_TEXT_11, 330, 7, 108, 22, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_12, 137, 118, 26, 28, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_13, 133, 117, 17, 14, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_14, 177, 9, 67, 20, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
uint8_t s=0,t=19;
/********************************************************************2020.10.29改动——————孙天一 1 start*********************************************************************************/
int speed_set, temperature_set = 18, model_set;
char* Speed_set[3] = {{"Low"}, {"Mid"}, {"High"}};
char* Model_set[3] = {{"Air"}, {"Warm"}, {"Cold"}};

extern RTC_TimeTypeDef sTime;//定义时间结构体
extern RTC_DateTypeDef sDate;

extern double temperature;
extern int menu;                                           //红外开关的命令状态，用#define数字的表示
extern int menu_temp;

extern RTC_HandleTypeDef hrtc;
extern TIM_HandleTypeDef htim3;
extern TIM_HandleTypeDef htim12;
/********************************************************************2020.10.29改动——————孙天一 1 start*********************************************************************************/
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END
  
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00C08080));
    //
    // Initialization of 'SPEED'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'N_TEM'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_24_1);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "2");
    //
    // Initialization of 'N_HUM'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetText(hItem, "3");
    TEXT_SetFont(hItem, GUI_FONT_24_1);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'M'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_24_1);
    TEXT_SetText(hItem, "Air");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'S'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_24_1);
    TEXT_SetText(hItem, "Low");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'N_TEM'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetText(hItem, "N_TEM");
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    //
    // Initialization of 'N_HUM'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    TEXT_SetText(hItem, "N_HUM");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'N_MODEL'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetText(hItem, "N_MODEL");
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    //
    // Initialization of 'N_SPEED'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetText(hItem, "N_SPEED");
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    //
    // Initialization of 'SET_TEM'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetText(hItem, "SET_TEM");
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    //
    // Initialization of '+'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetText(hItem, "rise");
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of '-'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetText(hItem, "reduce");
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'print tem'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
    TEXT_SetFont(hItem, GUI_FONT_32_1);
    TEXT_SetText(hItem, "18");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'MODEL'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'DATE'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
    TEXT_SetText(hItem, "2020/10/29");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'TIME'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
    TEXT_SetFont(hItem, GUI_FONT_32_1);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "00:09:30");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_12);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "C");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_13);
    TEXT_SetText(hItem, "o");
    TEXT_SetFont(hItem, GUI_FONT_10_1);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_14);
    TEXT_SetText(hItem, "TIME:");
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_24_1);
    // USER START (Optionally insert additional code for further widget initialization)
    WM_CreateTimer(pMsg->hWin, 0, 100, 0);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'SPEED'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        speed_set++;
        speed_set %= 3;
        //char buf[8];
        //sprintf(buf, "%s", Speed_set[speed_set]);
        //TEXT_SetText( WM_GetDialogItem(pMsg->hWin, ID_TEXT_3), buf);
        TEXT_SetText( WM_GetDialogItem(pMsg->hWin, ID_TEXT_3), Speed_set[speed_set]);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by '+'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        if (temperature_set >= 18 && temperature_set < 30)
          temperature_set++;
        char sprintf_buf[8];
        sprintf(sprintf_buf, "%d", temperature_set);
        TEXT_SetText( WM_GetDialogItem(pMsg->hWin, ID_TEXT_9), sprintf_buf);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by '-'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        if (temperature_set > 18 && temperature_set <= 30)
          temperature_set--;
        char buf[8];
        sprintf(buf, "%d", temperature_set);
        TEXT_SetText( WM_GetDialogItem(pMsg->hWin, ID_TEXT_9), buf);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'MODEL'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        model_set++;
        model_set %= 3;
        //char buf[8];
        //sprintf(buf, "%s", Model_set[model_set]);
        TEXT_SetText( WM_GetDialogItem(pMsg->hWin, ID_TEXT_2), Model_set[model_set]);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
      // USER START (Optionally insert additional code for further Ids)
      // USER END
    }
    break;
    // USER START (Optionally insert additional message handling)
  case WM_TIMER:    //屏幕时间显示
    
    WM_RestartTimer(pMsg->Data.v,100);
    HAL_RTC_GetTime(&hrtc, &sTime, RTC_FORMAT_BIN);
    HAL_RTC_GetDate(&hrtc, &sDate, RTC_FORMAT_BIN);    
    
    char buffer[8];
    sprintf(buffer,"%02d:%02d:%02d\r\n",sTime.Hours, sTime.Minutes, sTime.Seconds);
    TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_11),buffer);
    sprintf(buffer,"%01d/%02d/%02d\r\n",2000 + sDate.Year, sDate.Month, sDate.Date);
    TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_10),buffer);
    
    sprintf(buffer, "%4.2f", temperature);
    TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_0),buffer);
    
    if (temperature_set < 18) temperature_set = 18;
    sprintf(buffer, "%d", temperature_set);
    TEXT_SetText( WM_GetDialogItem(pMsg->hWin, ID_TEXT_9), buffer);
   
    if (speed_set == 3) speed_set = 2;
    sprintf(buffer, "%s", Speed_set[speed_set]);
    TEXT_SetText( WM_GetDialogItem(pMsg->hWin, ID_TEXT_3), buffer);
    
    sprintf(buffer, "%s", Model_set[model_set]);
    TEXT_SetText( WM_GetDialogItem(pMsg->hWin, ID_TEXT_2), buffer);
   
    __HAL_TIM_SET_COMPARE(&htim3, TIM_CHANNEL_1, 200 + speed_set * 400);
    if (model_set == 1)         //制热模式
    {
      uint16_t power;
      //如果屋里温度比设定冷，根据温度差值制热，温差越大功率越大，最大功率在屋里比设定低10℃时达到，输出最小功率为最大1/5（温度相等时候）
      if ((int)temperature < temperature_set)
      {
        if (temperature_set - temperature >= 10)
          power = 1000;
        else
        {
          power = 200 + (temperature_set - (int)temperature) * 800 / 10;             //最低200，最高1000
        }
      }
      //如果屋里温度高于设定，则温度越高制热功率越低，而且功率最大只能到达最大功率的1/5（认为这时候的空调功能主要是维持温度，而不是制热）
      else
      {
        if (temperature - temperature_set < 12)
          power = 200 - ((int)temperature - temperature_set) * 80 / 10;
        else power = 0;
      }  
      __HAL_TIM_SET_COMPARE(&htim12, TIM_CHANNEL_1,0);
      __HAL_TIM_SET_COMPARE(&htim12, TIM_CHANNEL_2,power);
    }
    else if (model_set == 2)    //制冷模式
    {
      uint16_t power;
      //如果屋里温度比设定热，根据温度差值制热，温差越大功率越大，最大功率在屋里比设定高10℃时达到，输出最小功率为最大1/5（温度相等时候）
      if ((int)temperature > temperature_set)
      {
        if (temperature - temperature_set >= 10)
          power = 1000;
        else
        {
          power = 200 + ((int)temperature - temperature_set) * 800 / 10;             //最低200，最高1000
        }
      }
      //如果屋里温度低于设定，则温度越低制热功率越低，而且功率最大只能到达最大功率的1/5（认为这时候的空调功能主要是维持温度，而不是制冷）
      else
      {
        if (temperature - temperature_set < 12)
          power = 200 - (temperature_set - (int)temperature) * 80 / 10;
        else power = 0;
      }  
      __HAL_TIM_SET_COMPARE(&htim12, TIM_CHANNEL_1,power);
      __HAL_TIM_SET_COMPARE(&htim12, TIM_CHANNEL_2,0);
    }
    else                                        //通风模式
    {
      __HAL_TIM_SET_COMPARE(&htim12, TIM_CHANNEL_1,0);
      __HAL_TIM_SET_COMPARE(&htim12, TIM_CHANNEL_2,0);
    }
    
    if (menu == SWITCH_ON) {
      HAL_GPIO_WritePin(GPIOK, GPIO_PIN_3, GPIO_PIN_SET);
    }
    else if (menu == SWITCH_OFF){
      HAL_GPIO_WritePin(GPIOK, GPIO_PIN_3, GPIO_PIN_RESET);
      __HAL_TIM_SET_COMPARE(&htim3, TIM_CHANNEL_1,0);
      __HAL_TIM_SET_COMPARE(&htim12, TIM_CHANNEL_1,0);
      __HAL_TIM_SET_COMPARE(&htim12, TIM_CHANNEL_2,0);
    }
    else {};
    
    break;
    // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;
  
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
